version: "3.3"
services:
  cdn_selection:
    #    image: alfg/nginx-rtmp
    build: .
    container_name: cdn_selection
    hostname: cdn_selection
    restart: always
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "5080:5080"
  prometheus:
    image: prom/prometheus
    #    build: .
#    network_mode: "host"
    container_name: prometheus1
    hostname: prometheus1
    restart: always
    volumes:
      - type: bind
        source: ./prometheus
        target: /etc/prometheus
    ports:
        - "5090:9090"
networks:
  default:
    external:
      name: external-example